### ISSUE TITLE
Improve scaling when using a large resolution

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/venus-html5-app#111]
Up to a certain resolution the boxes do not scale anymore as shown on the picture.

![image](https://user-images.githubusercontent.com/6614648/70700900-c5c23780-1ccb-11ea-869e-dc94a613bc9f.png)

**Comment by AlexImb** [comment]
It looks like the mobile detection is not working properly on that device. I changed the layout detection to only CSS rules instead of using a combination of `window.orientation` and User-Agent. Also, vertical scrolling is now enabled for small devices in portrait mode.

![simrad resolution 1280x720 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496934-1c25cf00-896a-11ea-8df2-6fbb4e43bb17.png)
![raymarine resolution 1280x800 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496938-1c25cf00-896a-11ea-8bf1-6bf3add55308.png)
![garmin resolution 640x723 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496943-1cbe6580-896a-11ea-910d-94034556a7eb.png)
![simrad resolution 543x772 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496944-1d56fc00-896a-11ea-8e79-11a61bfa7606.png)
![garmin resolution 1280x361 5 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496945-1def9280-896a-11ea-926f-332818d79ef4.png)
![simrad resolution 1086x386 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496948-1def9280-896a-11ea-82e4-f7c9b359483d.png)
![simrad resolution 362x772 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496949-1e882900-896a-11ea-9927-3eabaf1aeb48.png)
![garmin resolution 426 6666666666667x723 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496952-1e882900-896a-11ea-8988-e80fcb50e215.png)
![raymarine resolution 800x480 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496953-1f20bf80-896a-11ea-8de8-d8ecd894f34e.png)
![garmin resolution 640x361 5 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496957-1f20bf80-896a-11ea-9b40-6c2d54214b84.png)
![simrad resolution 543x386 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496958-1fb95600-896a-11ea-8864-30bfa287fb29.png)
![garmin resolution 426 6666666666667x361 5 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496960-1fb95600-896a-11ea-87f7-a8e7f58a2c3d.png)
![simrad resolution 362x386 -- Elements are in viewport -- main div](https://user-images.githubusercontent.com/4534299/80496962-2051ec80-896a-11ea-91df-81e3ec87730d.png)

550x900:
![image](https://user-images.githubusercontent.com/4534299/80497401-af5f0480-896a-11ea-9e26-0a89c3ce45e4.png)
