### ISSUE TITLE
Device tile has no buttons

### ISSUE THREAD

**Issue by Saharel001** [victronenergy/venus-html5-app#286]
My Multiplus device has no buttons yet. I use the Marine2 beta.
![image](https://user-images.githubusercontent.com/24453343/231839005-eb56c2a6-b0a9-426d-bb57-501c82ec4d85.png)

if i switch in .env.local to Marine it looks fine
![image](https://user-images.githubusercontent.com/24453343/231839848-b2fbeba1-730c-441a-8633-0b91c42a6e93.png)

**Comment by martinbosma** [comment]
Hi @Saharel001 the new version is still work in progress. When we release the first version of the new design we will make sure there will be working buttons.

**Comment by Saharel001** [comment]
Reopen: First release an the buttons still missing.

**Comment by martinbosma** [comment]
Yes, thank you for reporting. We're aware of it. Although this is now a release, it has not yet been fully tested and no final release has been made. We needed a release build to be able include it (temporarily) in a public beta Venus OS v3.00. This way people can see it, test it and give feedback.

Keep an eye on the Venus OS beta release thread on community. You can then give feedback there instead of creating issues here.

The final release of Venus OS v3.00 will not include the new version of html5 app, as it far from final.

________________________________
