### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/venus-html5-app#395]
With the new security profiles in Venus OS there was a Logout button added in the GUIv2. This should also be added to the MFD app in my opinion.

![grafik](https://github.com/user-attachments/assets/3cbd0525-0704-455e-be8a-530e45aae128)

When pressing the logout button in GUIv2 this code is executed, which opens the logout page from Venus OS:

```
void BackendConnection::logout()
{
#if defined(VENUS_WEBASSEMBLY_BUILD)
	emscripten_run_script("location.href = \'../auth/logout.php\';");
#endif
}
```

Maybe it would fit here?

![grafik](https://github.com/user-attachments/assets/7670ee4d-de07-4436-b3a0-a026f2126331)

https://github.com/victronenergy/venus-html5-app/blob/1cfc16d6271f29e2887df94d75db84810bd325b9/src/app/MarineApp/components/Header/Header.tsx#L52-L58

**Comment by mman** [comment]
@mr-manuel Some MFDs do not properly support HTTPS [citation needed] so current limitation is to keep Cerbo at `Unsecured` Security Profile in order for the HTML app to work properly. Also there does not seem to be an easy way to enter password on the MFD in order to authenticate. Closing now as will not fix. We will see how to address this in the future.
